<a href="https://colab.research.google.com/github/Henil21/PyTorch/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
!nvidia-smi

Wed Sep 25 07:46:28 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [11]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import sklearn
print(torch.__version__)


2.4.1+cu121




---



##Introduction to tensor🤝
### Creating tensors


>💡 A scalar is a single number and in tensor-speak it's a zero dimension tensor.

In [13]:
# Scaler
scaler=torch.tensor(7)
scaler

tensor(7)

In [18]:
scaler.ndim
# return dimensions

0

In [19]:
scaler.item()
# returns an python int

7

A vector is a single dimension tensor but can contain many numbers.

```As in, you could have a vector [3, 2] to describe [bedrooms, bathrooms] in your house. Or you could have [3, 2, 2] to describe [bedrooms, bathrooms, car_parks] in your house.```

The important trend here is that a vector is flexible in what it can represent (the same with tensors).

In [22]:
# vector
vector=torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape )

tensor([7, 7])
1
torch.Size([2])


In [27]:
# MATRIX
MATRIX=torch.tensor([[7,8],
                     [9,10]])
print(MATRIX)
print(MATRIX.ndim) #2d matrix
print(MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [26]:
print(f'first dimension is {MATRIX[0]}')
print(f'second dimension is {MATRIX[1]}')

first dimension is tensor([7, 8])
second dimension is tensor([ 9, 10])


In [30]:
TENSOR=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR
# this tensor are fundamental bilding block of nn

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [32]:
print(TENSOR.ndim)
TENSOR.shape

3


torch.Size([1, 3, 3])

In [35]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

<img src="https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png">



---



### Random Tensor ▶


We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've been doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

>**⚡ Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...**

> As a data scientist, you can define how the machine learning model starts (initialization), looks at data (representation) and updates (optimization) its random numbers.

We'll get hands on with these steps later on.

For now, let's see how to create a tensor of random numbers.

We can do so using `torch.rand()` and passing in the size parameter.

In [38]:
random_tensor=torch.rand(3,4) #size of (3,4)
random_tensor

tensor([[0.0810, 0.0831, 0.0121, 0.7377],
        [0.4294, 0.2500, 0.0402, 0.1565],
        [0.4067, 0.6205, 0.4781, 0.8288]])



---



The flexibility of `torch.rand()` is that *we can adjust the size to be whatever we want.*

For example, say **you wanted a random tensor in the common image shape of** `[224, 224, 3] ([height, width, color_channels]).`

In [39]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)



---



**This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).**

Let's create a tensor full of zeros with `torch.zeros()`

In [40]:
# Creating a tensor of all zeros
zero=torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [41]:
zero.dtype

torch.float32

### Creating a range of tensors and tensors like.🪞

In [43]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
range=torch.arange(start=0,end=10,step=2)
range

tensor([0, 2, 4, 6, 8])

In [48]:
# Creating tensor like
ten_zeros=torch.zeros_like(input=range)
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor datatypes ⬇

In [57]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # What device is your tensor on
                               requires_grad=False) # whether or not track gradients with this tensors operation

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [58]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)